// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvh6iUDuEfEfluq0ZCKINktPJ_0qk9HY',
    appId: '1:519910000342:android:0c7b6ec5d1e0815860ab77',
    messagingSenderId: '519910000342',
    projectId: 'playstorelaunch',
    databaseURL: 'https://playstorelaunch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playstorelaunch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaD1e71VEL8U5Dhrcv2g2sxl4ZKB06jw',
    appId: '1:519910000342:ios:11ee592af6c882bc60ab77',
    messagingSenderId: '519910000342',
    projectId: 'playstorelaunch',
    databaseURL: 'https://playstorelaunch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playstorelaunch.appspot.com',
    androidClientId: '519910000342-5c00jfklce040afb1n9ca2ugq7lfjnu8.apps.googleusercontent.com',
    iosClientId: '519910000342-fs8kif9d3upjs468jpm0ev5gu8c9i2gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocstudy',
  );
}
