[versions]
agp = "8.2.0-alpha06"
kotlin = "1.8.0"
core-ktx = "1.10.1"
junit = "4.13.2"
espresso-core = "3.5.1"
material = "1.9.0"

## common external lib
glide ="4.15.1"

## androidX lib common
androidxAppCompat = "1.6.1"
androidxActivityKTX = "1.7.2"
androidxlifecycleExtensions = "2.2.0"
androidxWorkKTX = "2.8.1"
androidFragmentKTX = "1.6.0"

## androidX lib TEST
androidx-test-ext-junit = "1.1.5"

## xml view lib
androixConstraintlayout = "2.1.4"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

## common external lib
glide = {group = "com.github.bumptexch.glide", name="glide", version.ref="glide"}

## androidX lib
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKTX" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidxlifecycleExtensions" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime", version.ref = "androidxWorkKTX" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidFragmentKTX" }

## xml view lib
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androixConstraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

[bundles]

